languageCode: en-us
title: GabrielFox.Dev
theme: 'PaperMod'

enableInlineShortcodes: true

# Search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

languages:
  en:
    languageName: 'English'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 'GabrielFox.Dev'
  description: 'GabrielFox Blog'
  author: GabrielFox

  defaultTheme: dark
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowRssButtonInSectionTermList: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ['title', 'permalink', 'summary', 'content']

  profileMode:
    enabled: false # needs to be explicitly set
    title: GabrielFox.Dev
    subtitle: ''
    imageUrl: '#'
    # imageWidth: 120
    # imageHeight: 120
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Gabriel's Replicated Weblog"
    Content: |
      Welcome to my redundant repository of random musings, side projects and tips & tricks.

      Fasten your seatbelts. 

      Replicas: 
      [Vercel](https://v.gabrielfox.dev) |
      [GitHub](https://g.gabrielfox.dev) |
      [Cloudflare](https://c.gabrielfox.dev) |
      [Netlify](https://n.gabrielfox.dev)
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/GabrielFoxDev'
    - name: github
      url: 'https://github.com/GabrielFoxDev'
    - name: linkedin
      url: 'https://linkedin.com/in/GabrielFoxDev'
    - name: rss
      url: index.xml
