name: Publish Site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: create gh-pages branch if not exist
        uses: christopherdavenport/create-ghpages-ifnotexists@v1

      - name: Publish Site
        uses: chabad360/hugo-gh-pages@e9fa2e522f33729260a177103c97bf3f8ca061c1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
